# Generated by Django 6.0.7 on 2026-08-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=32)),
                ('doc_key', models.CharField(max_length=64)),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('owner_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('category_path', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('text_extra', models.TextField(blank=True, default='')),
                ('text_plain', models.TextField(blank=True, default='')),
                ('facets', models.JSONField(blank=True, default=dict)),
                ('facet_terms', models.JSONField(blank=True, default=list)),
                ('price_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geohash', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('boost', models.FloatField(default=0.0)),
                ('promoted', models.BooleanField(default=False)),
                ('promotion_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card', models.JSONField(blank=True, default=dict)),
                ('source_seq', models.BigIntegerField(default=0)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_document',
                'indexes': [models.Index(fields=['doc_type', 'visible', '-published_at'], name='search_doc_recent_idx'), models.Index(fields=['doc_type', 'visible', 'price_base'], name='search_doc_price_idx'), models.Index(fields=['doc_type', 'owner_key'], name='search_doc_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'doc_key'), name='search_doc_identity')],
            },
        ),
        migrations.CreateModel(
            name='SearchSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=32)),
                ('doc_key', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('boost', 'boost'), ('popularity', 'popularity'), ('promoted', 'promoted')], max_length=16)),
                ('value', models.FloatField(default=0.0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'search_signal',
                'indexes': [models.Index(fields=['doc_type', 'doc_key'], name='search_signal_target_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='search.searchdocument')),
            ],
            options={
                'db_table': 'search_number',
                'indexes': [models.Index(fields=['slug', 'value'], name='search_number_range_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'slug'), name='search_number_identity')],
            },
        ),
    ]
